package com.sandu.quizz4games;

public class QuestionsEn {

    public String questions[] = {

            /*1*/  "Which is the first planet in the Solar system?",
            /*2*/  "Which is the second planet in the Solar system?",
            /*3*/  "Which is the third planet in the Solar system?",
            /*4*/  "Which is the fourth planet in the Solar system?",
            /*5*/  "Which is the fifth planet in the Solar system?",
            /*6*/  "Which is the sixth planet in the Solar system?",
            /*7*/  "Which is the seventh planet in the Solar system?",
            /*8*/  "Which is the eight planet in the Solar system?",
            /*9*/  "Which is the ninth planet in the Solar system?",
            /*10*/ "When was J.R.R Tolkien's 'The Lord of the Rings' first published?",
            /*11*/ "Which of these animals doesn't live in solitude?",
            /*12*/ "Which ideology proposes common ownership of the means of production?",
            /*13*/ "What unit of length is used in astronomy?",
            /*14*/ "Where did the Lumiere brothers screen their first films?",
            /*15*/ "What is a key component of hair and nails?",
            /*16*/ "Who wrote the novel 'Sense and Sensibility'? ",
            /*17*/ "Vivid dreams are likely to occur in what phase of the sleep cycle?",
            /*18*/ "Which theory explains how Earth's interior creates a magnetic field?",
            /*19*/ "Ashgabat is the capital of ...?",
            /*20*/ "What are the internal organs of a body?",
            /*21*/ "Which of these is NOT an Arabic-speaking country?",
            /*22*/ "What is the transformation from gaseous to liquid phase?",
            /*23*/ "Antananarivo is the capital of ...?",
            /*24*/ "Which is NOT an official language of Switzerland?",
            /*25*/ "A misanthrope dislikes ...?",
            /*26*/ "What does a hippopotamus primarily eats?",
            /*27*/ "Which country has an Islamic majority?",
            /*28*/ "What is the average speed of a car that travels 560km in 7 hours?",
            /*29*/ "What is the family of sunflowers (of daisies)?",
            /*30*/ "Which molecule is responsible for the unpleasant odor of human vomit?",
            /*31*/ "Which is a form of a male contraception?",
            /*32*/ "What are the first digits of pi?",
            /*33*/ "What is true for the South Pole?",
            /*34*/ "Which city is NOT the capital of its country?",
            /*35*/ "In August 1939, Germany signed a non-aggression pact with ...?",
            /*36*/ "What are Skaoi, Freya, and Iounn?",
            /*37*/ "Which of these dishes is NOT Italian?",
            /*38*/ "What Hindu greeting is spoken with hands pressed together and finger pointing upwards?",
            /*39*/ "Which is NOT used by a firefighter?",
            /*40*/ "Who was the founder of psychoanalysis?",
            /*41*/ "What is the capital of Northern Ireland?",
            /*42*/ "What is acetylsalicylic acid?",
            /*43*/ "Which vitamin cannot be found in a chicken egg?",
            /*44*/ "The Storting is the parliament of ...?",
            /*45*/ "'My handbag weighed a ton'",
            /*46*/ "Which type of memory allows us to unconsciously know how to tie our shoes?",
            /*47*/ "Where did the deportations and mass killings of Armenians in 1915 and 1916 take place?",
            /*48*/ "Which is a variable cost for a car manufacturer?",
            /*49*/ "Savoy is a historical region in ...?",
            /*50*/ "Which festival marks the end of Ramadan?",
            /*51*/ "'Tess of the d'Urbervilles' is a novel by ...?",
            /*52*/ "What is the unit for electrical impedance?",
            /*53*/ "Which is a famous street in Barcelona?",
            /*54*/ "What gives an inventor the right to stop other people from using their invention without permission?",
            /*55*/ "Which is a common move on the pommel horse?",
            /*56*/ "What does El Salvador mean?",
            /*57*/ "What method is used to determine the elemental composition of a sample?",
            /*58*/ "Which material created an economic boom in the Amazonian countries at the end of the 19th century?",
            /*59*/ "'Amphibian' comes from Greek and means ...?",
            /*60*/ "Which fish can spit a jet of water to shoot down land-based insects?",
            /*61*/ "The majority of the marsupial species live in ...?" ,
            /*62*/ "What is the capital of Chinese province Guangdong?",
            /*63*/ "Which English novelist wrote 'Wuthering Heights' ?",
            /*64*/ "The fall of Mohamed Siad Barre in 1991 led to Civil War in ...?",
            /*65*/ "Which is a characteristic of a tropical rainforest?",
            /*66*/ "Who wrote 'Call of the wild' and 'The Sed-Wolf'?",
            /*67*/ "What happens if you add salt to water?",
            /*68*/ "What is the main region of the voodoo religion?",
            /*69*/ "Which object is tidally locked with Earth?",
            /*70*/ "How many parties formed the government of the Soviet Union?",
            /*71*/ "What bird lays the largest eggs?",
            /*72*/ "Honey is mainly composed of ...?",
            /*73*/ "Which sport uses the terms 'forte' and 'foible'?",
            /*74*/ "What usually happens before a scientific paper can be published?",
            /*75*/ "What geological process enables paleontologists to study inner organs of fossils?",
            /*76*/ "Cheddar cheese originally comes from a region in ...?",
            /*77*/ "What is the inability to gain pleasure from normally pleasurable experiences?",
            /*78*/ "Who lived with chimpanzees for more than 30 years?",
            /*79*/ "What is the capital of China?",
            /*80*/ "Strychnine is ...?",
            /*81*/ "What battle was the turning point of the American Civil War?",
            /*82*/ "Which tecnology forms the basis for the vast majority of computers since the 1960s?",
            /*83*/ "What is a layer of rock in geology ?",
            /*84*/ "What do we call a business that lends and borrows money?",
            /*85*/ "What are molluscs?",
            /*86*/ "Where can we find the city of Lviv ?",
            /*87*/ "Which of these elements is an alkaline earth metal ?",
            /*88*/ "What chemical reaction releases energy from the system ?",
            /*89*/ "What is the most cultivated species of millet ?",
            /*90*/ "What is 'Solaris' in the film by Andrei Tarkovsky ?",
            /*91*/ "Which birds do NOT use their feet for walking ?",
            /*92*/ "The 9-hour long film 'Shoah' is a documentary about...?",
            /*93*/ "Who became the richest man of America when he retired from his steel business ?",
            /*94*/ "Who was a chancellor of West Germany ?",
            /*95*/ "What is the Palais Garnier in Paris ?",
            /*96*/ "Who was president of Cuba from 1976 to 2008 ?",
            /*97*/ "Which preofessional soldiers fight for money rather than for political interests ?",
            /*98*/ "Which ornate fish is known for its venomous spines ?",
            /*99*/ "How many centimeters are one meter ?",
            /*100*/"Which multiplication results in the highest number ?",
            /*101*/"Areceiving antenna converts radio waves into ...?",
            /*102*/"Which region has the highest biodiversity?",
            /*103*/"What neurons fire when an animal observes another animal performing the same action as itself at the same time ?",
            /*104*/"For what is 'Nikkei 225' used ?",
            /*105*/"Against whom did Donald Trump win the US presidential election of 2016 ?",
            /*106*/"Where did the My Lai Incident take place ?",
            /*107*/"Which is a result of conformity ?",
            /*108*/"What is the 'Promissed Land' in the Book of Exodus ?",
            /*109*/"Which is an Example of Moorish architecture ?",
            /*110*/"What British political association was in rivalry with the Whings in the 18th century ?"

    };

    private String choices [][] = {
            {"Mercury", "Venus", "Mars","Pluto"},
            {"Jupiter", "Venus", "Earth","Saturn"},
            {"Earth", "Jupiter", "Pluto","Mars"},
            {"Jupiter", "Saturn", "Mars","Mercury"},
            {"Jupiter", "Pluto", "Mercury","Venus"},
            {"Saturn", "Venus", "Mars","Jupiter"},
            {"Saturn", "Pluto", "Uranus","Mercury"},
            {"Mercury", "Neptune", "Mars","Earth"},
            {"Mercury", "Venus", "Pluto","Venus"},
            {"1954","1932","1941","1964"},
            {"Leopard","Opossum","Polar bear","Gorilla"},
            {"Nationalism","Pluralism","Despotism","Communism"},
            {"Weber","Pascal","Siemens","Parsec"},
            {"Paris","Marseille","London","Berlin"},
            {"Carotene","Chitin","Creatine","Keratin"},
            {"Charlotte Bronte","George Eliot","Ann Radcliffe","Jane Austen"},
            {"NREM 1","SWS","REM","NREM 2"},
            {"Messerschmitt theory","Dynamo theory","Expanding Earth theory","Vine-Matthews-Morley hypothesis"},
            {"Mongolia","Nepal","Turkmenistan","Afghanistan"},
            {"Viscera","Fenestre","Adumbrati","Sutures"},
            {"Algeria","Mozambique","Morocco","Sudan"},
            {"Melting","Boiling","Freezing","Condensation"},
            {"Chile","Madagascar","Philippines","Grenada"},
            {"French","German","Spanish","Italian"},
            {"Landscapes","Holidays","Animals","Humans"},
            {"Bark","Grass","Fish","Molluscs"},
            {"Israel","Armenia","Georgia","Azerbaijan"},
            {"60 km/h","80 km/h","90 km/h","70 km/h"},
            {"Asteraceae","Fabaceae","Ericaceae","Ribiaceae"},
            {"Thioacetone","Mercaptan","Hydrogen sulfide","Butyric acid"},
            {"Vasectomy","Phlebotomy","Pinealectomy","Colostomy"},
            {"1.34","4.31","3.41","3.14"},
            {"It is cooler then the North Pole","It lies on the ecuator","It doesn't have a landmass","It is home to the Polar Bear"},
            {"Berlin","Sofia","Oslo","Trondheim"},
            {"Poland","France","the United Kingdom","the Soviet Union"},
            {"Gods","Dishes","Islands","Crests"},
            {"Risotto","Lasagne","Sashimi","Pizza"},
            {"Anyoung haseyo","Namaste","Salaam","Habari"},
            {"Fire extinguisher","Fire hose","Ladder","Scalpel"},
            {"Sigmund Freud","Neils Bohr","Ludwig Wittgenstein","Ivan Pavlov"},
            {"Glasgow","Lancaster","Belfast","Dublin"},
            {"Anesthetic","Heparin","Aspirin","Heroin"},
            {"Vitamin E","Vitamin D","Vitamin C","Vitamin A"},
            {"Australia","Germany","Norway","Ireland"},
            {"Simile","Hyperbole","Allegory","Personification"},
            {"Episodic memory","Declarative memory","Procedural memory","Semantic memory"},
            {"Ottoman Empire","Soviet Union","Kingdom of Prusia","Habsburg Monarchy"},
            {"Insurance","Rent","Car components","Property tax"},
            {"Romania","Poland","Belgium","France"},
            {"Mardi Gras","Eid ul-Fitr","Gudi Padwa","Sebouha"},
            {"Alexander Palm","Henry Sacery","Thomas Hardy","Ramon Ortega y Frias"},
            {"Henry","Ohm","Watt/Meter","Siemens"},
            {"Rue des Barres","Via del Corso","La Rambla","Escadaria Selaron"},
            {"Embezzelement","Patent","Subpoena","Escrow"},
            {"Flare","Ollie","Iron cross","Casper"},
            {"The Sacred","The Good","The Savior","The Superior"},
            {"Mass nephelometry","Mass fluorimetry","Mass spectrometry","Mass odometry"},
            {"Diamonds","Platinum","Rubber","Phosphorus"},
            {"Double life","Sweatless","Water fowl","Self sustaining"},
            {"Archerfish","Lancetfish","Triggerfish","Lungfish"},
            {"Australia","Europe","North America","Africa"},
            {"Shanghai","Shantou","Wuhan","Guangzhou"},
            {"Emily Bronte","Charlotte Bronte","Anne Bronte","Elizabeth Bronte"},
            {"Kenya","Tanzania","Nigeria","Somalia"},
            {"High humidity","Cold climate","Low biodiversity","Little precipitation"},
            {"Gary Paulsen","Henry Longfellow","Rider Haggard","Jack London"},
            {"Surface tension decreases","Density decreases","Boiling point increases","Specific heat increases"},
            {"Sumba","Haiti","Java","Timor"},
            {"Sun","Moon","Venus","Mars"},
            {"1","3","2","4"},
            {"Blackbird","Penguin","Flamingo","Ostrich"},
            {"Lactose,Sucrose","Galactose,Trehalose","Glucose,Fructose","Fructose,Lactose"},
            {"Tennis","Fencing","Rugby","Karate"},
            {"Peer review","Putnam testing","Collateral check","Author's audit"},
            {"Permineralization","Metasomatism","Denudation","Phyllic alteration"},
            {"Ireland","Switzerland","Scotland","England"},
            {"Bruxism","Anhedonia","Amnesia","Encopresia"},
            {"Peter Kropotkin","James Dwight Dana","Jane Goodall","Desmond Morris"},
            {"Shanghai","Beijing","Hong Kong","Chongquing"},
            {"green","sweet","an amino acid","toxic"},
            {"Alamo","Iwo Jima","Waterloo","Gettysburg"},
            {"CMOS","Nanotube lattices","FinFET","PA-RISC"},
            {"Stratum","Tectum","Septum","Datum"},
            {"Pulp mill","Joint venture","Bank","Book Store"},
            {"Stars","Sediments","Plants","Animals"},
            {"Greece","Turkmenistan","Russia","Ukraine"},
            {"Magnesium","Copper","Phosphorus","Mercury"},
            {"Exothermic reaction","Transisent reaction","Endothermic reaction","Electromotive reaction"},
            {"Finger millet","Pearl millet","Proso millet","Koko millet"},
            {"Book","Planet","Dolphin","City"},
            {"Blackbirds","Hummingbirds","Storks","Swans"},
            {"the Holocaust","the Cold War","Japan","Christianity"},
            {"William Henry Vanderbilt","Salomon Oppenheim","Andrew Carnegie","Andrew W. Mellon"},
            {"Bruno Kreisky","Walter Thurnherr","Werner Faymann","Helmut Schmit"},
            {"Mausoleum","Museum","City Hall","Opera House"},
            {"Bill Clinton","Hugo Chavez","Fidel Castro","Evo Morales"},
            {"Emissaries","Centenaries","Missionaries","Mercenaries"},
            {"Triggerfish","Cardinalfish","Angelfish","Lionfish"},
            {"10","100","1000","10000"},
            {"23 x 3","13 x 6","18 x 4","8 x 9"},
            {"Laser beams","Mechanical waves","Electric current","Infrasound"},
            {"Daintree rainforest","Congo rainforest","Amazon rainforest","Borneo rainforest"},
            {"Pattern cells","Mirror neurons","Carbon cells","Echo neurons"},
            {"Stock investing","Energy production","Particle Acceleration","Air supremacy"},
            {"Hillary Clinton","Al Gore","Mitt Romney","Jhon Kerry"},
            {"Korea War","Six-Day War","Vietnam War","World War II"},
            {"Narcolepsy","Arrythmia","Free will","Groupthink"},
            {"Antioch","Palmyra","Canaan","Uruk"},
            {"Taj Mahal","Minangkabau Royal Palace","Hagia Sophia","Alhambra"},
            {"Tories","Republicans","England United","Rainbow"}




    };

    private String correctAnswers [] = {"Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune","Pluto","1954","Gorilla","Communism","Parsec","Paris","Keratin","Jane Austen","REM","Dynamo theory",
            "Turkmenistan","Viscera","Mozambique","Condensation","Madagascar","Spanish","Humans","Grass","Azerbaijan","80 km/h","Asteraceae","Butyric acid","Vasectomy","3.14",
            "It is cooler then the North Pole","Trondheim","the Soviet Union","Gods","Sashimi","Namaste","Scalpel","Sigmund Freud","Belfast","Aspirin","Vitamin C","Norway","Hyperbole",
            "Procedural memory","Ottoman Empire","Car components","France","Eid ul-Fitr","Thomas Hardy","Ohm","La Rambla","Patent","Flare","The Savior","Mass spectrometry","Rubber",
            "Double life","Archerfish","Australia","Guangzhou","Emily Bronte","Somalia","High humidity","Jack London","Boiling point increases","Haiti","Moon","1","Ostrich","Glucose,Fructose",
            "Fencing","Peer review","Permineralization","England","Anhedonia","Jane Goodall","Beijing","toxic","Gettysburg","CMOS","Stratum","Bank","Animals","Ukraine","Magnesium",
            "Exothermic reaction","Pearl millet","Planet","Hummingbirds","the Holocaust","Andrew Carnegie","Helmut Schmit","Opera House","Fidel Castro","Mercenaries","Lionfish","100","13 x 6","Electric current",
            "Amazon rainforest","Mirror neurons","Stock investing","Hillary Clinton","Vietnam War","Groupthink","Canaan","Alhambra","Tories"};


    public String getQuestions(int a){
        String question = questions[a];
        return question;
    }

    public String getChoice1 (int a){
        String choice = choices[a][0];
        return choice;
    }

    public String getChoice2 (int a){
        String choice = choices[a][1];
        return choice;
    }
    public String getChoice3 (int a){
        String choice = choices[a][2];
        return choice;
    }
    public String getChoice4 (int a){
        String choice = choices[a][3];
        return choice;
    }

    public String getCorrectAnswer (int a){
        String answer = correctAnswers[a];
        return answer;
    }


}
